In [1]:
import pandas as pd

In [ ]:
action_movies = pd.read_csv(r"C:\Users\aj824\Downloads\Ironhack Data Analytics 2024\Week 3 Project\week_3_project\imdb_movies_by_genre\action.csv")
action_movies

In [3]:
action_movies.rename(columns={'gross(in $)': 'gross'}, inplace=True)

In [4]:
action_movies.drop(columns=['star_id', 'director_id', 'description', 'star', 'gross'], inplace=True)

In [5]:
action_movies

,movie_id,movie_name,year,certificate,runtime,genre,rating,director,votes
0,tt9114286,Black Panther: Wakanda Forever,2022,PG-13,161 min,"Action, Adventure, Drama",6.9,Ryan Coogler,204835.0
1,tt1630029,Avatar: The Way of Water,2022,PG-13,192 min,"Action, Adventure, Fantasy",7.8,James Cameron,295119.0
2,tt5884796,Plane,2023,R,107 min,"Action, Thriller",6.5,Jean-François Richet,26220.0
3,tt6710474,Everything Everywhere All at Once,2022,R,139 min,"Action, Adventure, Comedy",8.0,"Dan Kwan, \r\nDaniel Scheinert",327858.0
4,tt5433140,Fast X,2023,NaN,NaN,"Action, Crime, Mystery",NaN,Louis Leterrier,NaN
...,...,...,...,...,...,...,...,...,...
52447,tt26743984,Suicide 2,1999,NaN,54 min,"Action, Drama, Horror",NaN,"Brandon Womeldorff, \r\nMatt Brassfield",NaN
52448,tt26744184,Chaos,2023,NaN,NaN,"Action, Thriller",NaN,"Aditi Prabhudeva, \r\nSiddu Moolimani, \r\nAks...",NaN
52449,tt26744484,Revolver Lily,NaN,NaN,NaN,"Action, Adventure",NaN,Isao Yukisada,NaN
52450,tt26744765,The Wing,NaN,NaN,NaN,Action,NaN,NaN,NaN
52451,tt26745202,Vey Dharuvey,NaN,NaN,NaN,"Action, Comedy",NaN,D. Naveen Reddy,NaN

In [8]:
action_movies.isna().sum()

movie_id           0
movie_name         0
year            8259
certificate    38784
runtime        19922
genre              0
rating         23004
director        4633
votes          23002
dtype: int64

In [9]:
action_movies['rating'].fillna('N/A', inplace=True)

In [10]:
action_movies.rating.unique

<bound method Series.unique of 0        6.9
1        7.8
2        6.5
3        8.0
4        N/A
        ...
52447    N/A
52448    N/A
52449    N/A
52450    N/A
52451    N/A
Name: rating, Length: 52452, dtype: object>

In [14]:
action_movies = action_movies[action_movies['rating'] != 'N/A']

In [15]:
action_movies

,movie_id,movie_name,year,certificate,runtime,genre,rating,director,votes
0,tt9114286,Black Panther: Wakanda Forever,2022,PG-13,161 min,"Action, Adventure, Drama",6.9,Ryan Coogler,204835.0
1,tt1630029,Avatar: The Way of Water,2022,PG-13,192 min,"Action, Adventure, Fantasy",7.8,James Cameron,295119.0
2,tt5884796,Plane,2023,R,107 min,"Action, Thriller",6.5,Jean-François Richet,26220.0
3,tt6710474,Everything Everywhere All at Once,2022,R,139 min,"Action, Adventure, Comedy",8.0,"Dan Kwan, \r\nDaniel Scheinert",327858.0
5,tt10954600,Ant-Man and the Wasp: Quantumania,2023,PG-13,125 min,"Action, Adventure, Comedy",6.6,Peyton Reed,5396.0
...,...,...,...,...,...,...,...,...,...
52393,tt1786705,The Hitch,2010,NaN,63 min,"Action, Comedy, Crime",6.4,Radu Vlad,12.0
52404,tt1930512,The Empty Hands,2011,R,90 min,Action,8.6,"Mahaliel Bethea, \r\nSteven Watkins",12.0
52413,tt0270820,Aag Ke Sholay,1988,NaN,138 min,"Action, Thriller",4.2,S.R. Pratap,10.0
52419,tt0432385,AK 47,2004,NaN,125 min,"Action, Thriller",5.2,Raam Shetty,45.0
52421,tt0465920,Black & Blue,2001,NaN,105 min,"Action, Drama",5.3,Tony Tite,38.0

In [16]:
action_movies['certificate'].fillna('N/A', inplace=True)

In [17]:
action_movies

,movie_id,movie_name,year,certificate,runtime,genre,rating,director,votes
0,tt9114286,Black Panther: Wakanda Forever,2022,PG-13,161 min,"Action, Adventure, Drama",6.9,Ryan Coogler,204835.0
1,tt1630029,Avatar: The Way of Water,2022,PG-13,192 min,"Action, Adventure, Fantasy",7.8,James Cameron,295119.0
2,tt5884796,Plane,2023,R,107 min,"Action, Thriller",6.5,Jean-François Richet,26220.0
3,tt6710474,Everything Everywhere All at Once,2022,R,139 min,"Action, Adventure, Comedy",8.0,"Dan Kwan, \r\nDaniel Scheinert",327858.0
5,tt10954600,Ant-Man and the Wasp: Quantumania,2023,PG-13,125 min,"Action, Adventure, Comedy",6.6,Peyton Reed,5396.0
...,...,...,...,...,...,...,...,...,...
52393,tt1786705,The Hitch,2010,N/A,63 min,"Action, Comedy, Crime",6.4,Radu Vlad,12.0
52404,tt1930512,The Empty Hands,2011,R,90 min,Action,8.6,"Mahaliel Bethea, \r\nSteven Watkins",12.0
52413,tt0270820,Aag Ke Sholay,1988,N/A,138 min,"Action, Thriller",4.2,S.R. Pratap,10.0
52419,tt0432385,AK 47,2004,N/A,125 min,"Action, Thriller",5.2,Raam Shetty,45.0
52421,tt0465920,Black & Blue,2001,N/A,105 min,"Action, Drama",5.3,Tony Tite,38.0

In [18]:
print(action_movies['votes'].dtype)

float64

In [20]:
action_movies['votes'] = action_movies['votes'].astype(int)
action_movies['rating'] = action_movies['rating'].astype(float)

In [21]:
action_movies

,movie_id,movie_name,year,certificate,runtime,genre,rating,director,votes
0,tt9114286,Black Panther: Wakanda Forever,2022,PG-13,161 min,"Action, Adventure, Drama",6.9,Ryan Coogler,204835
1,tt1630029,Avatar: The Way of Water,2022,PG-13,192 min,"Action, Adventure, Fantasy",7.8,James Cameron,295119
2,tt5884796,Plane,2023,R,107 min,"Action, Thriller",6.5,Jean-François Richet,26220
3,tt6710474,Everything Everywhere All at Once,2022,R,139 min,"Action, Adventure, Comedy",8.0,"Dan Kwan, \r\nDaniel Scheinert",327858
5,tt10954600,Ant-Man and the Wasp: Quantumania,2023,PG-13,125 min,"Action, Adventure, Comedy",6.6,Peyton Reed,5396
...,...,...,...,...,...,...,...,...,...
52393,tt1786705,The Hitch,2010,N/A,63 min,"Action, Comedy, Crime",6.4,Radu Vlad,12
52404,tt1930512,The Empty Hands,2011,R,90 min,Action,8.6,"Mahaliel Bethea, \r\nSteven Watkins",12
52413,tt0270820,Aag Ke Sholay,1988,N/A,138 min,"Action, Thriller",4.2,S.R. Pratap,10
52419,tt0432385,AK 47,2004,N/A,125 min,"Action, Thriller",5.2,Raam Shetty,45
52421,tt0465920,Black & Blue,2001,N/A,105 min,"Action, Drama",5.3,Tony Tite,38

In [22]:
# Suponiendo que action_movies es tu DataFrame y las columnas se llaman 'votes', 'movie_name' y 'rating'
top_movies = action_movies[['movie_name', 'votes', 'rating']].sort_values(by='votes', ascending=False).head(10)
print(top_movies)

                                            movie_name    votes  rating
33                                     The Dark Knight  2675531     9.0
34                                           Inception  2373682     8.8
52                                          The Matrix  1928021     8.7
28   The Lord of the Rings: The Fellowship of the Ring  1889727     8.8
74       The Lord of the Rings: The Return of the King  1860374     9.0
115                              The Dark Knight Rises  1717874     8.4
111              The Lord of the Rings: The Two Towers  1679818     8.8
38                                           Gladiator  1512747     8.5
164                                      Batman Begins  1482505     8.2
184                                       The Avengers  1400257     8.0

In [23]:
# Ordenamos las películas por la cantidad de votos en orden descendente
sorted_movies = action_movies.sort_values(by='votes', ascending=False)

# Seleccionamos la película con la mayor calificación de entre las primeras
top_rated_movie = sorted_movies.iloc[0]

# Mostramos la película con la mayor calificación entre las más votadas
print("Película con más votos y mayor rating:")
print("Nombre:", top_rated_movie['movie_name'])
print("Votos:", top_rated_movie['votes'])
print("Rating:", top_rated_movie['rating'])

Película con más votos y mayor rating:
Nombre: The Dark Knight
Votos: 2675531
Rating: 9.0

In [30]:
# Ordenamos las películas por la cantidad de votos en orden descendente
sorted_movies = action_movies.sort_values(by='votes', ascending=False)
sorted_movies.reset_index(drop = True, inplace = True)
sorted_movies.index += 1
# Seleccionamos las 10 películas con más votos
top_10_movies = sorted_movies.head(10)

# De las 10 películas seleccionadas, encontramos aquella con el mayor rating
top_rated_movie = top_10_movies.loc[top_10_movies['rating'].idxmax()]

# Mostramos las 10 películas con más votos y la película con el mayor rating entre ellas
print("Las 10 películas con más votos:")
print(top_10_movies[['movie_name', 'votes', 'rating']])
print("\nPelícula con más votos y mayor rating:")
print("Nombre:", top_rated_movie['movie_name'])
print("Votos:", top_rated_movie['votes'])
print("Rating:", top_rated_movie['rating'])

Las 10 películas con más votos:
                                           movie_name    votes  rating
1                                     The Dark Knight  2675531     9.0
2                                           Inception  2373682     8.8
3                                          The Matrix  1928021     8.7
4   The Lord of the Rings: The Fellowship of the Ring  1889727     8.8
5       The Lord of the Rings: The Return of the King  1860374     9.0
6                               The Dark Knight Rises  1717874     8.4
7               The Lord of the Rings: The Two Towers  1679818     8.8
8                                           Gladiator  1512747     8.5
9                                       Batman Begins  1482505     8.2
10                                       The Avengers  1400257     8.0

Película con más votos y mayor rating:
Nombre: The Dark Knight
Votos: 2675531
Rating: 9.0

In [33]:
top_10_movies

,movie_id,movie_name,year,certificate,runtime,genre,rating,director,votes
33,tt0468569,The Dark Knight,2008,PG-13,152 min,"Action, Crime, Drama",9.0,Christopher Nolan,2675531
34,tt1375666,Inception,2010,PG-13,148 min,"Action, Adventure, Sci-Fi",8.8,Christopher Nolan,2373682
52,tt0133093,The Matrix,1999,R,136 min,"Action, Sci-Fi",8.7,"Lana Wachowski, \r\nLilly Wachowski",1928021
28,tt0120737,The Lord of the Rings: The Fellowship of the Ring,2001,PG-13,178 min,"Action, Adventure, Drama",8.8,Peter Jackson,1889727
74,tt0167260,The Lord of the Rings: The Return of the King,2003,PG-13,201 min,"Action, Adventure, Drama",9.0,Peter Jackson,1860374
115,tt1345836,The Dark Knight Rises,2012,PG-13,164 min,"Action, Drama",8.4,Christopher Nolan,1717874
111,tt0167261,The Lord of the Rings: The Two Towers,2002,PG-13,179 min,"Action, Adventure, Drama",8.8,Peter Jackson,1679818
38,tt0172495,Gladiator,2000,R,155 min,"Action, Adventure, Drama",8.5,Ridley Scott,1512747
164,tt0372784,Batman Begins,2005,PG-13,140 min,"Action, Crime, Drama",8.2,Christopher Nolan,1482505
184,tt0848228,The Avengers,2012,PG-13,143 min,"Action, Sci-Fi",8.0,Joss Whedon,1400257

In [31]:
# Ordenamos las películas por la cantidad de votos en orden descendente
sorted_movies = action_movies.sort_values(by='votes', ascending=False)

# Seleccionamos las 10 películas con más votos
top_10_movies = sorted_movies.head(10)

# De las 10 películas seleccionadas, encontramos aquella con el mayor rating
top_rated_movie = top_10_movies.loc[top_10_movies['rating'].idxmax()]

# Mostramos las 10 películas con más votos y la película con el mayor rating entre ellas
print("Las 10 películas con más votos:")
print(top_10_movies[['movie_name', 'director', 'votes', 'rating']])
print("\nPelícula con más votos y mayor rating:")
print("Nombre:", top_rated_movie['movie_name'])
print("Director:", top_rated_movie['director'])
print("Votos:", top_rated_movie['votes'])
print("Rating:", top_rated_movie['rating'])

Las 10 películas con más votos:
                                            movie_name  \
33                                     The Dark Knight
34                                           Inception
52                                          The Matrix
28   The Lord of the Rings: The Fellowship of the Ring
74       The Lord of the Rings: The Return of the King
115                              The Dark Knight Rises
111              The Lord of the Rings: The Two Towers
38                                           Gladiator
164                                      Batman Begins
184                                       The Avengers

                                director    votes  rating
33                     Christopher Nolan  2675531     9.0
34                     Christopher Nolan  2373682     8.8
52   Lana Wachowski, \r\nLilly Wachowski  1928021     8.7
28                         Peter Jackson  1889727     8.8
74                         Peter Jackson  1860374     9.0
115                    Christopher Nolan  1717874     8.4
111                        Peter Jackson  1679818     8.8
38                          Ridley Scott  1512747     8.5
164                    Christopher Nolan  1482505     8.2
184                          Joss Whedon  1400257     8.0

Película con más votos y mayor rating:
Nombre: The Dark Knight
Director: Christopher Nolan
Votos: 2675531
Rating: 9.0

# Alejandro Figueroa Dev Space

In [63]:
import requests
import pandas as pd

url = "https://moviesdatabase.p.rapidapi.com/titles/{id}"
querystring = {"info":"revenue_budget"}

headers = {
	"x-rapidapi-key": "9292e06bc9msh8780a7a7cba2601p11bfb1jsn413dded59c5d",
	"x-rapidapi-host": "moviesdatabase.p.rapidapi.com",
	"Content-Type": "application/json"
}

# Function to format a value as currency
def format_currency(value):
    return "${:,.2f}".format(value)

# Function to send movie_id to API
def send_movie_id(movie_id):
    response = requests.get(url.format(id=movie_id), headers=headers, params=querystring)
    
    if response.status_code == 200:
        return response.json()
    else:
        print("Could not get response from API")
    
    

# Iterate over DataFrame and send each movie_id
def get_worldwide_gross_movie(movie_df):
    
    # This list will store the values for gross of each movie
    gross_list = []
    try: 
        for movie_id in movie_df['movie_id']:
            response = send_movie_id(movie_id)
            gross_list.append(format_currency(response['results']['worldwideGross']['total']['amount']))
        
        movie_df['worldwide_gross'] = gross_list
    except Exception as e:
        print(f"Could not get response from API: {e}")

In [70]:
def get_top_10_movies(csv_path):
    try:
        # Create dataframe from CSV file
        movie_df = pd.read_csv(csv_path)
        
        # Drop unnecessary columns
        movie_df.drop(columns=['star_id', 'director_id', 'description', 'star', 'gross(in $)'], inplace=True)
        
        # Fill null values in columns we will use for analysis
        movie_df['rating'].fillna('N/A', inplace=True)
        movie_df['certificate'].fillna('N/A', inplace=True)
        
        # Cleanup in the director column
        movie_df['director'].apply(lambda name: str(name).replace("\r\n","&"))
        
        # Filtering for movies that have a rating
        movie_df = movie_df[movie_df['rating'] != 'N/A']
        
        # Changing data type for columns
        movie_df['votes'] = movie_df['votes'].astype(int)
        movie_df['rating'] = movie_df['rating'].astype(float)
        
        # Sort movies in descending order by votes and rating
        movie_df.sort_values(by=['votes', 'rating'], ascending=[False, False], inplace=True)
        
        # Reset index to 0 and start at 1
        movie_df.reset_index(drop = True, inplace = True)
        movie_df.index += 1
        
        top_movies = movie_df.head(10)
        
        return top_movies    
        
    except Exception as e:
        print(f"Error getting your top 10 movies: {e}")

## Top 10 Action Movies

In [64]:
top_10_action_movies = get_top_10_movies(r"C:\Users\aj824\Downloads\Ironhack Data Analytics 2024\Week 3 Project\week_3_project\imdb_movies_by_genre\action.csv")

get_worldwide_gross_movie(top_10_action_movies)
top_10_action_movies

,movie_id,movie_name,year,certificate,runtime,genre,rating,director,votes,worldwide_gross
1,tt0468569,The Dark Knight,2008,PG-13,152 min,"Action, Crime, Drama",9.0,Christopher Nolan,2675531,"$1,005,973,645.00"
2,tt1375666,Inception,2010,PG-13,148 min,"Action, Adventure, Sci-Fi",8.8,Christopher Nolan,2373682,"$836,836,967.00"
3,tt0133093,The Matrix,1999,R,136 min,"Action, Sci-Fi",8.7,"Lana Wachowski, \r\nLilly Wachowski",1928021,"$466,625,730.00"
4,tt0120737,The Lord of the Rings: The Fellowship of the Ring,2001,PG-13,178 min,"Action, Adventure, Drama",8.8,Peter Jackson,1889727,"$897,690,072.00"
5,tt0167260,The Lord of the Rings: The Return of the King,2003,PG-13,201 min,"Action, Adventure, Drama",9.0,Peter Jackson,1860374,"$1,146,030,912.00"
6,tt1345836,The Dark Knight Rises,2012,PG-13,164 min,"Action, Drama",8.4,Christopher Nolan,1717874,"$1,081,142,612.00"
7,tt0167261,The Lord of the Rings: The Two Towers,2002,PG-13,179 min,"Action, Adventure, Drama",8.8,Peter Jackson,1679818,"$947,495,095.00"
8,tt0172495,Gladiator,2000,R,155 min,"Action, Adventure, Drama",8.5,Ridley Scott,1512747,"$465,380,802.00"
9,tt0372784,Batman Begins,2005,PG-13,140 min,"Action, Crime, Drama",8.2,Christopher Nolan,1482505,"$373,661,946.00"
10,tt0848228,The Avengers,2012,PG-13,143 min,"Action, Sci-Fi",8.0,Joss Whedon,1400257,"$1,518,815,515.00"

## Top 10 Animated Movies

In [72]:
top_10_animated_movies = get_top_10_movies(r"C:\Users\aj824\Downloads\Ironhack Data Analytics 2024\Week 3 Project\week_3_project\imdb_movies_by_genre\animation.csv")

get_worldwide_gross_movie(top_10_animated_movies)
top_10_animated_movies

,movie_id,movie_name,year,certificate,runtime,genre,rating,director,votes,worldwide_gross
1,tt0910970,WALL·E,2008,G,98 min,"Animation, Adventure, Family",8.4,Andrew Stanton,1129202,"$521,311,890.00"
2,tt0110357,The Lion King,1994,G,88 min,"Animation, Adventure, Drama",8.5,"Roger Allers, \r\nRob Minkoff",1071452,"$1,063,611,805.00"
3,tt1049413,Up,2009,PG,96 min,"Animation, Adventure, Comedy",8.3,"Pete Docter, \r\nBob Peterson",1056429,"$735,099,102.00"
4,tt0266543,Finding Nemo,2003,G,100 min,"Animation, Adventure, Comedy",8.2,"Andrew Stanton, \r\nLee Unkrich",1055181,"$940,352,645.00"
5,tt0114709,Toy Story,1995,G,81 min,"Animation, Adventure, Comedy",8.3,John Lasseter,1005692,"$394,436,586.00"
6,tt0198781,"Monsters, Inc.",2001,G,92 min,"Animation, Adventure, Comedy",8.1,"Pete Docter, \r\nDavid Silverman, \r\nLee Unkrich",920933,"$579,707,738.00"
7,tt0435761,Toy Story 3,2010,G,103 min,"Animation, Adventure, Comedy",8.3,Lee Unkrich,845710,"$1,066,970,811.00"
8,tt0245429,Spirited Away,2001,PG,125 min,"Animation, Adventure, Family",8.6,Hayao Miyazaki,776225,"$355,706,103.00"
9,tt0382932,Ratatouille,2007,G,111 min,"Animation, Adventure, Comedy",8.1,"Brad Bird, \r\nJan Pinkava",752449,"$623,726,085.00"
10,tt0892769,How to Train Your Dragon,2010,PG,98 min,"Animation, Action, Adventure",8.1,"Dean DeBlois, \r\nChris Sanders",751157,"$494,879,471.00"

## Top 10 Horror Movies

In [73]:
top_10_horror_movies = get_top_10_movies(r"C:\Users\aj824\Downloads\Ironhack Data Analytics 2024\Week 3 Project\week_3_project\imdb_movies_by_genre\horror.csv")

get_worldwide_gross_movie(top_10_horror_movies)
top_10_horror_movies

,movie_id,movie_name,year,certificate,runtime,genre,rating,director,votes,worldwide_gross
1,tt0081505,The Shining,1980,R,146 min,"Drama, Horror",8.4,Stanley Kubrick,1032203,"$46,998,772.00"
2,tt0078748,Alien,1979,R,117 min,"Horror, Sci-Fi",8.5,Ridley Scott,890417,"$106,285,522.00"
3,tt0480249,I Am Legend,2007,PG-13,101 min,"Action, Drama, Horror",7.2,Francis Lawrence,768223,"$585,410,052.00"
4,tt0054215,Psycho,1960,R,109 min,"Horror, Mystery, Thriller",8.5,Alfred Hitchcock,677535,"$32,041,845.00"
5,tt0816711,World War Z,2013,PG-13,116 min,"Action, Adventure, Horror",7.0,Marc Forster,676411,"$540,455,876.00"
6,tt0144084,American Psycho,2000,R,102 min,"Crime, Drama, Horror",7.6,Mary Harron,636221,"$34,266,564.00"
7,tt5052448,Get Out,2017,R,104 min,"Horror, Mystery, Thriller",7.7,Jordan Peele,624515,"$255,589,157.00"
8,tt1156398,Zombieland,2009,R,88 min,"Action, Comedy, Horror",7.6,Ruben Fleischer,585822,"$102,392,080.00"
9,tt0365748,Shaun of the Dead,2004,R,99 min,"Comedy, Horror",7.9,Edgar Wright,564467,"$30,097,092.00"
10,tt1396484,It,2017,R,135 min,Horror,7.3,Andy Muschietti,557690,"$701,796,444.00"

## Top 10 Thriller Movies

In [75]:
top_10_thriller_movies = get_top_10_movies(r"C:\Users\aj824\Downloads\Ironhack Data Analytics 2024\Week 3 Project\week_3_project\imdb_movies_by_genre\thriller.csv")

get_worldwide_gross_movie(top_10_thriller_movies)
top_10_thriller_movies

,movie_id,movie_name,year,certificate,runtime,genre,rating,director,votes,worldwide_gross
1,tt0468569,The Dark Knight,2008,PG-13,152 min,"Action, Crime, Drama",9.0,Christopher Nolan,2675531,"$1,005,973,645.00"
2,tt1375666,Inception,2010,PG-13,148 min,"Action, Adventure, Sci-Fi",8.8,Christopher Nolan,2373682,"$836,836,967.00"
3,tt0114369,Se7en,1995,R,127 min,"Crime, Drama, Mystery",8.6,David Fincher,1668095,"$327,333,559.00"
4,tt0102926,The Silence of the Lambs,1991,R,118 min,"Crime, Drama, Thriller",8.6,Jonathan Demme,1444522,"$272,742,922.00"
5,tt0482571,The Prestige,2006,PG-13,130 min,"Drama, Mystery, Sci-Fi",8.5,Christopher Nolan,1344449,"$109,676,311.00"
6,tt0407887,The Departed,2006,R,151 min,"Crime, Drama, Thriller",8.5,Martin Scorsese,1335810,"$291,465,373.00"
7,tt1130884,Shutter Island,2010,R,138 min,"Mystery, Thriller",8.2,Martin Scorsese,1332201,"$294,805,697.00"
8,tt7286456,Joker,2019,R,122 min,"Crime, Drama, Thriller",8.4,Todd Phillips,1310698,"$1,074,419,384.00"
9,tt0209144,Memento,2000,R,113 min,"Mystery, Thriller",8.4,Christopher Nolan,1247771,"$40,047,078.00"
10,tt0110413,Léon: The Professional,1994,R,110 min,"Action, Crime, Drama",8.5,Luc Besson,1171574,"$19,552,639.00"

## Top 10 Thriller Movies

In [76]:
top_10_fantasy_movies = get_top_10_movies(r"C:\Users\aj824\Downloads\Ironhack Data Analytics 2024\Week 3 Project\week_3_project\imdb_movies_by_genre\fantasy.csv")

get_worldwide_gross_movie(top_10_fantasy_movies)
top_10_fantasy_movies

,movie_id,movie_name,year,certificate,runtime,genre,rating,director,votes,worldwide_gross
1,tt0120737,The Lord of the Rings: The Fellowship of the Ring,2001,PG-13,178 min,"Action, Adventure, Drama",8.8,Peter Jackson,1889727,"$897,690,072.00"
2,tt0167260,The Lord of the Rings: The Return of the King,2003,PG-13,201 min,"Action, Adventure, Drama",9.0,Peter Jackson,1860374,"$1,146,030,912.00"
3,tt0167261,The Lord of the Rings: The Two Towers,2002,PG-13,179 min,"Action, Adventure, Drama",8.8,Peter Jackson,1679818,"$947,495,095.00"
4,tt0076759,Star Wars,1977,PG,121 min,"Action, Adventure, Fantasy",8.6,George Lucas,1374568,"$775,398,007.00"
5,tt0499549,Avatar,2009,PG-13,162 min,"Action, Adventure, Fantasy",7.9,James Cameron,1322694,"$2,847,246,203.00"
6,tt0120689,The Green Mile,1999,R,189 min,"Crime, Drama, Fantasy",8.6,Frank Darabont,1313365,"$286,801,374.00"
7,tt0080684,Star Wars: Episode V - The Empire Strikes Back,1980,PG,124 min,"Action, Adventure, Fantasy",8.7,Irvin Kershner,1302151,"$538,375,067.00"
8,tt0325980,Pirates of the Caribbean: The Curse of the Bla...,2003,PG-13,143 min,"Action, Adventure, Fantasy",8.1,Gore Verbinski,1137362,"$654,264,015.00"
9,tt0086190,Star Wars: Episode VI - Return of the Jedi,1983,PG,131 min,"Action, Adventure, Fantasy",8.3,Richard Marquand,1062181,"$475,106,177.00"
10,tt0114709,Toy Story,1995,G,81 min,"Animation, Adventure, Comedy",8.3,John Lasseter,1002538,"$394,436,586.00"

## Top 10 Film Noir Movies

In [78]:
top_10_filmnoir_movies = get_top_10_movies(r"C:\Users\aj824\Downloads\Ironhack Data Analytics 2024\Week 3 Project\week_3_project\imdb_movies_by_genre\film-noir.csv")

get_worldwide_gross_movie(top_10_filmnoir_movies)
top_10_filmnoir_movies

,movie_id,movie_name,year,certificate,runtime,genre,rating,director,votes,worldwide_gross
1,tt0043014,Sunset Blvd.,1950,N/A,110 min,"Drama, Film-Noir",8.4,Billy Wilder,224111,"$300,073.00"
2,tt0041959,The Third Man,1949,U,104 min,"Film-Noir, Mystery, Thriller",8.1,Carol Reed,173375,"$1,226,797.00"
3,tt0033870,The Maltese Falcon,1941,N/A,100 min,"Crime, Film-Noir, Mystery",8.0,John Huston,160669,"$16,511.00"
4,tt0036775,Double Indemnity,1944,N/A,107 min,"Crime, Drama, Film-Noir",8.3,Billy Wilder,158953,"$14,190.00"
5,tt0032976,Rebecca,1940,N/A,130 min,"Drama, Film-Noir, Mystery",8.1,Alfred Hitchcock,138938,"$72,275.00"
6,tt0044079,Strangers on a Train,1951,A,101 min,"Crime, Drama, Film-Noir",7.9,Alfred Hitchcock,135584,"$1,494.00"
7,tt0052311,Touch of Evil,1958,PG-13,95 min,"Crime, Drama, Film-Noir",8.0,Orson Welles,105973,"$2,286,947.00"
8,tt0038787,Notorious,1946,U,102 min,"Drama, Film-Noir, Romance",7.9,Alfred Hitchcock,102645,"$113,061.00"
9,tt0049406,The Killing,1956,N/A,84 min,"Crime, Drama, Film-Noir",8.0,Stanley Kubrick,91399,$203.00
10,tt0048424,The Night of the Hunter,1955,A,92 min,"Crime, Drama, Film-Noir",8.0,Charles Laughton,91172,"$2,001.00"