In [ ]:
import pandas as pd

In [ ]:
action_movies = pd.read_csv('action.csv')
action_movies

,movie_id,movie_name,year,certificate,runtime,genre,rating,description,director,director_id,star,star_id,votes,gross(in $)
0,tt9114286,Black Panther: Wakanda Forever,2022,PG-13,161 min,"Action, Adventure, Drama",6.9,The people of Wakanda fight to protect their h...,Ryan Coogler,/name/nm3363032/,"Letitia Wright, \nLupita Nyong'o, \nDanai Guri...","/name/nm4004793/,/name/nm2143282/,/name/nm1775...",204835.0,NaN
1,tt1630029,Avatar: The Way of Water,2022,PG-13,192 min,"Action, Adventure, Fantasy",7.8,Jake Sully lives with his newfound family form...,James Cameron,/name/nm0000116/,"Sam Worthington, \nZoe Saldana, \nSigourney We...","/name/nm0941777/,/name/nm0757855/,/name/nm0000...",295119.0,NaN
2,tt5884796,Plane,2023,R,107 min,"Action, Thriller",6.5,A pilot finds himself caught in a war zone aft...,Jean-Fran√ßois Richet,/name/nm0724938/,"Gerard Butler, \nMike Colter, \nTony Goldwyn, ...","/name/nm0124930/,/name/nm1591496/,/name/nm0001...",26220.0,NaN
3,tt6710474,Everything Everywhere All at Once,2022,R,139 min,"Action, Adventure, Comedy",8.0,A middle-aged Chinese immigrant is swept up in...,"Dan Kwan, \nDaniel Scheinert",/name/nm3453283/,"Michelle Yeoh, \nStephanie Hsu, \nJamie Lee Cu...","/name/nm3215397/,/name/nm0000706/,/name/nm3513...",327858.0,NaN
4,tt5433140,Fast X,2023,NaN,NaN,"Action, Crime, Mystery",NaN,Dom Toretto and his family are targeted by the...,Louis Leterrier,/name/nm0504642/,"Vin Diesel, \nJordana Brewster, \nTyrese Gibso...","/name/nm0004874/,/name/nm0108287/,/name/nm0879...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52447,tt26743984,Suicide 2,1999,NaN,54 min,"Action, Drama, Horror",NaN,Matt awakens after trying to end his own life ...,"Brandon Womeldorff, \nMatt Brassfield",/name/nm13690776/,"Matt Hoffman, \nMatt Brassfield, \nBrandon Wom...","/name/nm1565857/,/name/nm7326486/,/name/nm1565...",NaN,NaN
52448,tt26744184,Chaos,2023,NaN,NaN,"Action, Thriller",NaN,Add a Plot,"Aditi Prabhudeva, \nSiddu Moolimani, \nAkshith...",/name/nm8898786/,NaN,"/name/nm7465869/,/name/nm12502668/,/name/nm545...",NaN,NaN
52449,tt26744484,Revolver Lily,NaN,NaN,NaN,"Action, Adventure",NaN,"Takes place in 1924 and centres on Yuri, who k...",Isao Yukisada,/name/nm0950834/,NaN,NaN,NaN,NaN
52450,tt26744765,The Wing,NaN,NaN,NaN,Action,NaN,The most secret and elite Special Forces unit ...,NaN,NaN,NaN,NaN,NaN,NaN
52451,tt26745202,Vey Dharuvey,NaN,NaN,NaN,"Action, Comedy",NaN,Add a Plot,D. Naveen Reddy,/name/nm14569102/,"Sunil, \nHebah Patel, \nKrishna Murali Posani,...","/name/nm1198628/,/name/nm6171293/,/name/nm0692...",NaN,NaN

In [ ]:
action_movies.rename(columns={'gross(in $)': 'gross'}, inplace=True)

In [ ]:
action_movies.drop(columns=['star_id', 'director_id', 'description', 'movie_id', 'star', 'gross'], inplace=True)

In [ ]:
action_movies

,movie_name,year,certificate,runtime,genre,rating,director,votes
0,Black Panther: Wakanda Forever,2022,PG-13,161 min,"Action, Adventure, Drama",6.9,Ryan Coogler,204835.0
1,Avatar: The Way of Water,2022,PG-13,192 min,"Action, Adventure, Fantasy",7.8,James Cameron,295119.0
2,Plane,2023,R,107 min,"Action, Thriller",6.5,Jean-Fran√ßois Richet,26220.0
3,Everything Everywhere All at Once,2022,R,139 min,"Action, Adventure, Comedy",8.0,"Dan Kwan, \nDaniel Scheinert",327858.0
4,Fast X,2023,NaN,NaN,"Action, Crime, Mystery",NaN,Louis Leterrier,NaN
...,...,...,...,...,...,...,...,...
52447,Suicide 2,1999,NaN,54 min,"Action, Drama, Horror",NaN,"Brandon Womeldorff, \nMatt Brassfield",NaN
52448,Chaos,2023,NaN,NaN,"Action, Thriller",NaN,"Aditi Prabhudeva, \nSiddu Moolimani, \nAkshith...",NaN
52449,Revolver Lily,NaN,NaN,NaN,"Action, Adventure",NaN,Isao Yukisada,NaN
52450,The Wing,NaN,NaN,NaN,Action,NaN,NaN,NaN
52451,Vey Dharuvey,NaN,NaN,NaN,"Action, Comedy",NaN,D. Naveen Reddy,NaN

In [ ]:
action_movies.rating.isna

<bound method Series.isna of 0        6.9
1        7.8
2        6.5
3        8.0
4        NaN
        ...
52447    NaN
52448    NaN
52449    NaN
52450    NaN
52451    NaN
Name: rating, Length: 52452, dtype: float64>

In [ ]:
action_movies['rating'].fillna('unknown', inplace=True)

/var/folders/0c/c54kvlxj57j55xl482xz8qdr0000gn/T/ipykernel_1317/3742941066.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  action_movies['rating'].fillna('unknown', inplace=True)

In [ ]:
action_movies.rating.unique

<bound method Series.unique of 0            6.9
1            7.8
2            6.5
3            8.0
4        unknown
          ...
52447    unknown
52448    unknown
52449    unknown
52450    unknown
52451    unknown
Name: rating, Length: 52452, dtype: object>

In [ ]:
action_movies = action_movies[action_movies['rating'] != 'unknown']

In [ ]:
action_movies

,movie_name,year,certificate,runtime,genre,rating,director,votes
0,Black Panther: Wakanda Forever,2022,PG-13,161 min,"Action, Adventure, Drama",6.9,Ryan Coogler,204835.0
1,Avatar: The Way of Water,2022,PG-13,192 min,"Action, Adventure, Fantasy",7.8,James Cameron,295119.0
2,Plane,2023,R,107 min,"Action, Thriller",6.5,Jean-Fran√ßois Richet,26220.0
3,Everything Everywhere All at Once,2022,R,139 min,"Action, Adventure, Comedy",8.0,"Dan Kwan, \nDaniel Scheinert",327858.0
5,Ant-Man and the Wasp: Quantumania,2023,PG-13,125 min,"Action, Adventure, Comedy",6.6,Peyton Reed,5396.0
...,...,...,...,...,...,...,...,...
52393,The Hitch,2010,NaN,63 min,"Action, Comedy, Crime",6.4,Radu Vlad,12.0
52404,The Empty Hands,2011,R,90 min,Action,8.6,"Mahaliel Bethea, \nSteven Watkins",12.0
52413,Aag Ke Sholay,1988,NaN,138 min,"Action, Thriller",4.2,S.R. Pratap,10.0
52419,AK 47,2004,NaN,125 min,"Action, Thriller",5.2,Raam Shetty,45.0
52421,Black & Blue,2001,NaN,105 min,"Action, Drama",5.3,Tony Tite,38.0

In [ ]:
action_movies['certificate'].fillna('unknown', inplace=True)

/var/folders/0c/c54kvlxj57j55xl482xz8qdr0000gn/T/ipykernel_1317/1991332335.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  action_movies['certificate'].fillna('unknown', inplace=True)

In [ ]:
action_movies

,movie_name,year,certificate,runtime,genre,rating,director,votes
0,Black Panther: Wakanda Forever,2022,PG-13,161 min,"Action, Adventure, Drama",6.9,Ryan Coogler,204835.0
1,Avatar: The Way of Water,2022,PG-13,192 min,"Action, Adventure, Fantasy",7.8,James Cameron,295119.0
2,Plane,2023,R,107 min,"Action, Thriller",6.5,Jean-Fran√ßois Richet,26220.0
3,Everything Everywhere All at Once,2022,R,139 min,"Action, Adventure, Comedy",8.0,"Dan Kwan, \nDaniel Scheinert",327858.0
5,Ant-Man and the Wasp: Quantumania,2023,PG-13,125 min,"Action, Adventure, Comedy",6.6,Peyton Reed,5396.0
...,...,...,...,...,...,...,...,...
52393,The Hitch,2010,unknown,63 min,"Action, Comedy, Crime",6.4,Radu Vlad,12.0
52404,The Empty Hands,2011,R,90 min,Action,8.6,"Mahaliel Bethea, \nSteven Watkins",12.0
52413,Aag Ke Sholay,1988,unknown,138 min,"Action, Thriller",4.2,S.R. Pratap,10.0
52419,AK 47,2004,unknown,125 min,"Action, Thriller",5.2,Raam Shetty,45.0
52421,Black & Blue,2001,unknown,105 min,"Action, Drama",5.3,Tony Tite,38.0

In [ ]:
print(action_movies['votes'].dtype)

float64

In [ ]:
action_movies['votes'] = action_movies['votes'].astype(int)

/var/folders/0c/c54kvlxj57j55xl482xz8qdr0000gn/T/ipykernel_1317/1052088565.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  action_movies['votes'] = action_movies['votes'].astype(int)

In [ ]:
action_movies

,movie_name,year,certificate,runtime,genre,rating,director,votes
0,Black Panther: Wakanda Forever,2022,PG-13,161 min,"Action, Adventure, Drama",6.9,Ryan Coogler,204835
1,Avatar: The Way of Water,2022,PG-13,192 min,"Action, Adventure, Fantasy",7.8,James Cameron,295119
2,Plane,2023,R,107 min,"Action, Thriller",6.5,Jean-Fran√ßois Richet,26220
3,Everything Everywhere All at Once,2022,R,139 min,"Action, Adventure, Comedy",8.0,"Dan Kwan, \nDaniel Scheinert",327858
5,Ant-Man and the Wasp: Quantumania,2023,PG-13,125 min,"Action, Adventure, Comedy",6.6,Peyton Reed,5396
...,...,...,...,...,...,...,...,...
52393,The Hitch,2010,unknown,63 min,"Action, Comedy, Crime",6.4,Radu Vlad,12
52404,The Empty Hands,2011,R,90 min,Action,8.6,"Mahaliel Bethea, \nSteven Watkins",12
52413,Aag Ke Sholay,1988,unknown,138 min,"Action, Thriller",4.2,S.R. Pratap,10
52419,AK 47,2004,unknown,125 min,"Action, Thriller",5.2,Raam Shetty,45
52421,Black & Blue,2001,unknown,105 min,"Action, Drama",5.3,Tony Tite,38

In [ ]:
# Suponiendo que action_movies es tu DataFrame y las columnas se llaman 'votes', 'movie_name' y 'rating'
top_movies = action_movies[['movie_name', 'votes', 'rating']].sort_values(by='votes', ascending=False).head(10)
print(top_movies)

                                            movie_name    votes rating
33                                     The Dark Knight  2675531    9.0
34                                           Inception  2373682    8.8
52                                          The Matrix  1928021    8.7
28   The Lord of the Rings: The Fellowship of the Ring  1889727    8.8
74       The Lord of the Rings: The Return of the King  1860374    9.0
115                              The Dark Knight Rises  1717874    8.4
111              The Lord of the Rings: The Two Towers  1679818    8.8
38                                           Gladiator  1512747    8.5
164                                      Batman Begins  1482505    8.2
184                                       The Avengers  1400257    8.0

In [ ]:
# Ordenamos las pel√≠culas por la cantidad de votos en orden descendente
sorted_movies = action_movies.sort_values(by='votes', ascending=False)

# Seleccionamos la pel√≠cula con la mayor calificaci√≥n de entre las primeras
top_rated_movie = sorted_movies.iloc[0]

# Mostramos la pel√≠cula con la mayor calificaci√≥n entre las m√°s votadas
print("Pel√≠cula con m√°s votos y mayor rating:")
print("Nombre:", top_rated_movie['movie_name'])
print("Votos:", top_rated_movie['votes'])
print("Rating:", top_rated_movie['rating'])

Pel√≠cula con m√°s votos y mayor rating:
Nombre: The Dark Knight
Votos: 2675531
Rating: 9.0

In [ ]:
# Ordenamos las pel√≠culas por la cantidad de votos en orden descendente
sorted_movies = action_movies.sort_values(by='votes', ascending=False)

# Seleccionamos las 10 pel√≠culas con m√°s votos
top_10_movies = sorted_movies.head(10)

# De las 10 pel√≠culas seleccionadas, encontramos aquella con el mayor rating
top_rated_movie = top_10_movies.loc[top_10_movies['rating'].idxmax()]

# Mostramos las 10 pel√≠culas con m√°s votos y la pel√≠cula con el mayor rating entre ellas
print("Las 10 pel√≠culas con m√°s votos:")
print(top_10_movies[['movie_name', 'votes', 'rating']])
print("\nPel√≠cula con m√°s votos y mayor rating:")
print("Nombre:", top_rated_movie['movie_name'])
print("Votos:", top_rated_movie['votes'])
print("Rating:", top_rated_movie['rating'])

Las 10 pel√≠culas con m√°s votos:
                                            movie_name    votes rating
33                                     The Dark Knight  2675531    9.0
34                                           Inception  2373682    8.8
52                                          The Matrix  1928021    8.7
28   The Lord of the Rings: The Fellowship of the Ring  1889727    8.8
74       The Lord of the Rings: The Return of the King  1860374    9.0
115                              The Dark Knight Rises  1717874    8.4
111              The Lord of the Rings: The Two Towers  1679818    8.8
38                                           Gladiator  1512747    8.5
164                                      Batman Begins  1482505    8.2
184                                       The Avengers  1400257    8.0

Pel√≠cula con m√°s votos y mayor rating:
Nombre: The Dark Knight
Votos: 2675531
Rating: 9.0

In [ ]:
# Ordenamos las pel√≠culas por la cantidad de votos en orden descendente
sorted_movies = action_movies.sort_values(by='votes', ascending=False)

# Seleccionamos las 10 pel√≠culas con m√°s votos
top_10_movies = sorted_movies.head(10)

# De las 10 pel√≠culas seleccionadas, encontramos aquella con el mayor rating
top_rated_movie = top_10_movies.loc[top_10_movies['rating'].idxmax()]

# Mostramos las 10 pel√≠culas con m√°s votos y la pel√≠cula con el mayor rating entre ellas
print("Las 10 pel√≠culas con m√°s votos:")
print(top_10_movies[['movie_name', 'director', 'votes', 'rating']])
print("\nPel√≠cula con m√°s votos y mayor rating:")
print("Nombre:", top_rated_movie['movie_name'])
print("Director:", top_rated_movie['director'])
print("Votos:", top_rated_movie['votes'])
print("Rating:", top_rated_movie['rating'])

Las 10 pel√≠culas con m√°s votos:
                                            movie_name  \
33                                     The Dark Knight
34                                           Inception
52                                          The Matrix
28   The Lord of the Rings: The Fellowship of the Ring
74       The Lord of the Rings: The Return of the King
115                              The Dark Knight Rises
111              The Lord of the Rings: The Two Towers
38                                           Gladiator
164                                      Batman Begins
184                                       The Avengers

                              director    votes rating
33                   Christopher Nolan  2675531    9.0
34                   Christopher Nolan  2373682    8.8
52   Lana Wachowski, \nLilly Wachowski  1928021    8.7
28                       Peter Jackson  1889727    8.8
74                       Peter Jackson  1860374    9.0
115                  Christopher Nolan  1717874    8.4
111                      Peter Jackson  1679818    8.8
38                        Ridley Scott  1512747    8.5
164                  Christopher Nolan  1482505    8.2
184                        Joss Whedon  1400257    8.0

Pel√≠cula con m√°s votos y mayor rating:
Nombre: The Dark Knight
Director: Christopher Nolan
Votos: 2675531
Rating: 9.0